### ISSUE TITLE
Error messages when using WUFI to create a baseline model

### ISSUE THREAD

**Issue by SmartOwls** [PH-Tools/CarbonCheck#9]
I'm trying to create a baseline model from WUFI and I followed the instruction here:
https://ph-tools.github.io/CarbonCheck/baselines/

When I click "Create the Baseline Model" on step 4, this shows up on the window below without giving me a baseline model

>     Setting Baseline values on the WUFI File: 'C:\Users\phsu\Desktop\Bank Loft MF.xml'
>     Reading in the WUFI-XML file: 'Bank Loft MF.xml'
>     Converting WUFI-XML data to a new PHX Model
>     Using climate-zone: 'CZ5 (and Marine 4)' for baseline.
>     Using PF-Group: 'Under 0.2' for baseline.
>     Using Use-Group: 'Group R' for baseline.
>     Setting Baseline values...
>     Setting Baseline opaque envelope U-values.
>     Setting Baseline window U-values.
>     Using baseline window U-Value: 2.555 for all windows.
>     Using baseline window SHGC: 0.38 for all windows.
>     Collecting the unique 'PhxComponentAperture' types in the PHX-Project: 'unnamed_project'.
>     Creating a new baseline 'PhxConstructionWindow' for each unique 'PhxComponentAperture' type.
>     Setting all 'PhxConstructionWindow' to the baseline types.
>     Setting Baseline window areas.
>     division by zero
>     Traceback (most recent call last):
>       File "D:\a\CarbonCheck\CarbonCheck\CC_GUI\cc_workers.py", line 599, in run
>       File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\ph_baseliner\phx\windows.py", line 116, in set_baseline_window_area
>     ZeroDivisionError: division by zero

**Comment by ed-p-may** [comment]
Hello @SmartOwls , 

Thank you for reporting this error. It looks like the error is occurring when the baseliner attempts to divide the  aperture-area by the gross-wall-area. For some reason the gross-wall-area is being reported as Zero, which appear to be causing the error. Can you share a bit more about your WUFI model? Either screen shots, or the actual .mwp file, if you are able?

@ed-p-may

**Comment by SmartOwls** [comment]
Hello @ed-p-may,

I'd be happy to attach the WUFI file for you privately. 
I originally tried reaching out to the email listed on your website (CarbonCheck@PassiveHouseAccelerator.com), but my message was returned. 
Could you please provide a correct email address for me to contact?

**Comment by ed-p-may** [comment]
Thanks for letting me know about the email issue - I'll check on that and see what the issue is. Feel free to email me directly at any time at ED@BLDGTYP.COM - happy to take a look at the file and see if we can determine what the trouble is.
